# Copyright (c) 2021 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 
title: "Deploy a containerized WordPress instance on OCI"
description: "Deploy containerized WordPress & MySQL on OCI using a single compute instance. "
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - instance_os
  - linux_os_version
  - label_prefix

- title: WordPress Configuration
  visible: true  
  variables:
    - wp_admin_user
    - wp_admin_password
    - show_advanced

- title: MySQL Configuration
  visible: 
      and:
        - show_advanced  
  variables:
    - wp_db_user
    - wp_schema



- title: Instance Configuration
  visible: 
      and:
        - show_advanced
  variables:
    - compartment_ocid
    - availability_domain_name 
    - instance_shape
    - instance_ocpus
    - instance_shape_config_memory_in_gbs
    - generate_public_ssh_key
    - public_ssh_key


- title: Network Configuration
  visible: 
      and:
        - show_advanced
  variables:
     - vcn
     - vcn_cidr

outputGroups:
- title: Service Endpoints
  outputs:
    - wordpress_public_ip
    - wordpress_admin_url
- title: Generated Passwords
  outputs:
    - generated_ssh_private_key

outputs:
  wordpress_public_ip:
    type: link
    title: Your WordPress website
    description: Open WordPress website
  wordpress_admin_url:
    type: link
    title: WordPress Login
    description: Login to your WordPress installation.
  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    description: "Generated SSH Private Key"
    type: copyableString
    visible: true

primaryOutputButton: wordpress_admin_url

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

# MySQL

  wp_db_user:
    type: string
    required: false
    title: "WordPress database username"
    description: "The username that WordPress uses to connect to the MySQL database."
    minLength: 2
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    visible: 
      and:
        - show_advanced

  wp_schema:
    type: string
    required: false
    title: "MySQL schema to be used by WordPress"
    description: "The MySQL Schema/Database for WordPress."
    visible: 
      and:
        - show_advanced
  
  wp_admin_user:
    type: string
    required: true
    title: "WordPress admin username"
    description: "The username for the WordPress administrator."
    minLength: 2
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    visible: true

  wp_admin_password:
    type: password
    required: true
    title: "WordPress admin password"
    description: "The password should be more than 8 characters and must include an uppercase, lowercase, numeral and one of the following special characters : !@#%^*_+-:?.,[]{}"
    #pattern: "^(?=[a-zA-Z0-9!@#%^*_+\-:?.,\[\]\{\}]{8,32}$)(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9]).*"
    pattern: "^(?=.*[!@#%^*_+\\-:?.,\\[\\]\\{\\}])(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,32}$"
  
# Network
  vcn:
    type: string
    visible: 
      and:
        - show_advanced
    required: true
    title: "VCN name"
    description: "Type VCN name where your WordPress will be deployed."

  vcn_cidr:
    type: string
    visible: 
      and:
        - show_advanced
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose VCN CIDR for your WordPress deployment."

# Instance 
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visible: 
      and:
        - show_advanced
    title: "Compartment"
    description: "Compartment where your WordPress will be deployed."

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visible: 
      and:
        - show_advanced
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your WordPress will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  instance_shape:
    type: oci:core:instanceshape:name
    required: false
    visible: 
      and:
        - show_advanced
    title: "Wordpress node shape"
    description: "Choose Instance Shape for WordPress host."
    default: "VM.Standard.E3.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}
  
  instance_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    title: "Number of OCPUs"
    description: "You can customize the number of OCPUs to a flexible shape."
    visible:
      and:
        - show_advanced
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.E4.Flex"

  instance_shape_config_memory_in_gbs:
    type: integer
    minimum: 1
    maximum: 1024
    title: "Amount of memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - show_advanced
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.E4.Flex"

  instance_os:
    type: enum
    required: false
    visible: 
      and:
        - show_advanced
    title: "Instance OS"
    description: "An Operating System that determines the operating system for WordPress host."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    visible: 
      and:
        - show_advanced
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for WordPress host."
    default: "7.8"
    enum:
      - "7.8"

  label_prefix:
    type: string
    required: false
    visible: false
    title: "WordPress Hostname Prefix"
    description: "Type WordPress Hostname Prefix."

  

  generate_public_ssh_key:
    type: boolean
    title: "Auto generate public ssh key?"
    required: true
    visible: #($show_advanced  == ""Yes"")
      and:
        - show_advanced 

  public_ssh_key:
    type: oci:core:ssh:publickey
    title: "Import your own SSH public key"
    additionalProps:
      allowMultiple: true
    description: "In order to access your private nodes with a public SSH key you will need to set up a bastion host (a.k.a. jump box). If using public nodes, bastion is not needed. Left blank to not import keys."
    required: false
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible: 
      and:
        - show_advanced
        - not:
          - generate_public_ssh_key

