#cloud-config
# Copyright (c) 2021 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 
bootcmd:
  - [ cloud-init-per, once, enable-epel,  yum-config-manager, --enable, ol7_developer_epel]
groups:
  - docker
users:
  - default 
  - name: opc
    groups: docker
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

packages:
 - docker-engine
 - docker-compose

runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, docker.service ]
  - [ systemctl, start, --no-block, docker.service ]
  - [ touch, /tmp/cloud-init-complete ]
