title: "Deploy WordPress CMS VM, MySQL VM and Matomo VM on OCI"
stackDescription: "Deploy WordPress CMS VM, MySQL VM and Matomo VM on OCI"
schemaVersion: 1.2.0
version: "20201104"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - release

- title: Required Configuration
  visible: true  
  variables:
  - compartment_ocid
  - availablity_domain_name 
  - admin_password
  - wp_password
  - wp_site_admin_pass
  - matomo_password
  - show_advanced

- title: Network Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - vcn
  - vcn_cidr

- title: Compute Instances Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - ssh_public_key
  - instance_os
  - linux_os_version
  - label_prefix
  - node_shape
  - node_flex_shape_ocpus
  - node_flex_shape_memory

- title: WordPress Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - wp_site_admin_email
  - wp_site_admin_user
  - wp_plugins
  - wp_themes
  - wp_name
  - wp_schema
  - wp_site_url
  - wp_site_title

- title: MySQL Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - mysql_version
  - admin_username

- title: Matomo Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - matomo_username
  - matomo_schema

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: "Compartment"
    description: "Compartment where your WordPress and Matomo will be deployed."

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: "Region"
    description: "Choose Region where your WordPress and Matomo will be deployed."

  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your WordPress and Matomo will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Public SSH Key"
    description: "Choose public SSH Key to be uploaded into compute instances."
    required: false

  admin_password:
    type: password
    required: true
    title: "MySQL Admin User's Password"
    description: "Choose password for MySQL Database System admin user."
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"

  wp_password:
    type: password
    required: true
    title: "MySQL WordPress User's Password"
    description: "Choose MySQL Password for WordPress User."
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"

  matomo_password:
    type: password
    required: true
    title: "MySQL Matomo User's Password"
    description: "Choose MySQL Password for Matomo User."
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{8,32}$"

  wp_site_title:
    type: string
    required: false
    visible: true
    title: "WordPress Site Title"
    description: "Define WordPress Site Title"

  wp_site_admin_user:
    type: string
    required: true
    visible: true
    default: "admin"
    title: "WordPress Site Admin Username"
    description: "Define WordPress Site Admin Username"

  wp_site_admin_pass:
    type: password
    required: true
    visible: true
    title: "WordPress Site Admin Password"
    description: "Define WordPress Site Admin Password"
  
  wp_site_admin_email:
    type: string
    visible: true
    required: true
    default: "admin@example.com"
    title: "WordPress Site Admin Email"
    description: "Define WordPress Site Admin E-mail"

  matomo_username:
    type: string
    visible: true
    required: true
    default: "matomo"
    title: "Matomo Username"
    description: "Define Matomo Username"

  matomo_schema:
    type: string
    visible: true
    required: true
    default: "matomo"
    title: "MySQL Matomo Schema"
    description: "Define MySQL Matomo Schema"

  vcn:
    type: string
    visible: false
    required: true
    title: "VCN name"
    description: "Type VCN name where your WordPress and Matomo will be deployed."

  vcn_cidr:
    type: string
    visible: false
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose VCN CIDR for your WordPress and Matomo deployments."


  node_shape:
    type: oci:core:instanceshape:name
    required: false
    title: "Wordpress and Matomo compute shape"
    description: "Choose Instance Shape for WordPress and Matomo compute instances."
    default: "VM.Standard.A1.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}

  node_flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - node_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - node_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - node_shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - node_shape 
            - "VM.Optimized3.Flex"

  node_flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 10
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - node_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - node_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - node_shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - node_shape 
            - "VM.Optimized3.Flex"

  instance_os:
    type: enum
    required: false
    visible: true
    title: "Instance OS"
    description: "An Operating System that determines the operating system for WordPress and Matomo hosts."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    visible: true
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for WordPress and Matomo hosts."
    default: "8"
    enum:
      - "7.9"
      - "8"
  
  mysql_version:
    type: enum
    required: false
    default: "8.0.23"
    title: "MySQL Version"
    description: "Choose MySQL version."
    enum:
      - "8.0.23"

  label_prefix:
    type: string
    required: false
    visible: false
    title: "WordPress Hostname Prefix"
    description: "Type WordPress Hostname Prefix."

  admin_username:
    type: string
    required: false
    title: "MySQL Admin Username"
    description: "Type MySQL Database admin username."
    minLength: 1
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"

  wp_name:
    type: string
    required: false
    title: "MySQL WordPress Username"
    description: "Type MySQL Username for WordPress."
    minLength: 2
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"

  wp_schema:
    type: string
    required: false
    title: "MySQL WordPress Schema"
    description: "Type MySQL Schema/Database for WordPress."

  wp_plugins:
    type: array
    items:
      type: string
      pattern: "^[a-zA-Z0-9\\-]+$"
    required: true
    title: "WordPress Plugins"
    default: ["hello-dolly","elementor"]
    minItems: 1
    uniqueItems: true
    description: "Define WordPress Plugins to be installed with wp-cli (minimum 1 plugin)."

  wp_themes:
    type: array
    items:
      type: string
      pattern: "^[a-zA-Z0-9\\-]+$"
    required: true
    title: "WordPress Themes"
    default: ["lodestar", "twentysixteen"]
    minItems: 1
    uniqueItems: true
    description: "Define WordPress Themes to be installed with wp-cli (minimum 1 theme)."

  wp_site_url:
    type: string
    required: false
    title: "WordPress Site URL"
    description: "Define WordPress Site URL"

outputs:

  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: copyableString
    visible: true

  wordpress_wp-admin_url:
    title: "WordPress CMS WP-Admin URL"
    displayText: "WordPress CMS WP-Admin URL"
    type: string
    visible: true

  wordpress_wp-admin_user:
    title: "WordPress CMS WP-Admin User"
    displayText: "WordPress CMS WP-Admin User"
    type: string
    visible: true

  wordpress_wp-admin_password:
    title: "WordPress CMS WP-Admin Password"
    displayText: "WordPress CMS WP-Admin Password"
    type: string
    visible: true

  wordpress_public_ip:
    title: "WordPress CMS Public IP"
    displayText: "WordPress CMS Public IP"
    type: string
    visible: true

  matomo_public_ip:
    title: "Matomo Public IP"
    displayText: "Matomo Public IP"
    type: string
    visible: true

  matomo_url:
    title: "Matomo URL"
    displayText: "Matomo URL"
    type: string
    visible: true

  matomo_username:
    title: "Matomo MySQL Database Username"
    displayText: "Matomo MySQL Database Username"
    type: string
    visible: true

  matomo_password:
    title: "Matomo MySQL Database User Password"
    displayText: "Matomo MySQL Database User Password"
    type: string
    visible: true

  matomo_schema:
    title: "Matomo MySQL Database (Schema)"
    displayText: "Matomo MySQL Database (Schema)"
    type: string
    visible: true

  mysql_instance_ip:
    title: "MySQL instance private IP"
    displayText: "MySQL instance private IP"
    type: string
    visible: true
    